"""
Base Strategy Interface
=======================
Defines the standard contract for all trading strategies in the platform.
Supports plug-and-play strategy development and independent ablation testing.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
import pandas as pd

from app.models import (
    Candle,
    SignalDirection,
    EvidenceItem,
    MultiAttributeRegime,
)


@dataclass
class StrategyContext:
    """Consolidated market data & features passed into strategies."""
    symbol: str
    candles: List[Candle]
    df_enriched: pd.DataFrame
    regime: MultiAttributeRegime
    extra_timeframe_candles: Dict[str, List[Candle]] = field(default_factory=dict)


@dataclass
class StrategySignalResult:
    """Output generated by a single strategy."""
    strategy_name: str
    direction: SignalDirection
    confidence: float            # 0.0 to 1.0 (strategy internal conviction)
    evidence_items: List[EvidenceItem] = field(default_factory=list)
    suggested_expiry_seconds: int = 300
    metadata: Dict[str, Any] = field(default_factory=dict)


class BaseStrategy(ABC):
    """Abstract Base Class for all signal-generating strategies."""

    name: str = "BaseStrategy"
    version: str = "1.0.0"
    description: str = ""
    target_regimes: List[str] = []
    prohibited_regimes: List[str] = []
    min_adx: float = 0.0

    @abstractmethod
    def evaluate(self, ctx: StrategyContext) -> Optional[StrategySignalResult]:
        """
        Evaluates the current market state and returns a StrategySignalResult if a setup is detected.
        Must be strictly causal (only past data up to the current candle).
        """
        pass

    def is_regime_compatible(self, regime: MultiAttributeRegime) -> bool:
        """Checks if current market regime permits this strategy to run."""
        # 1. ADX Floor Check
        if self.min_adx > 0.0 and regime.adx_value < self.min_adx:
            return False

        # 2. Prohibited Regimes Gating (e.g. no Trend in RANGING markets)
        if self.prohibited_regimes:
            if regime.structure.value in self.prohibited_regimes:
                return False
            if regime.trend.value in self.prohibited_regimes:
                return False

        # 3. Target Regimes Filter (if specified)
        if self.target_regimes:
            return regime.structure.value in self.target_regimes or regime.trend.value in self.target_regimes

        return True
